### ISSUE TITLE
CRITICAL ISSUE: Unable to finish deployment because the deployment is failing

### ISSUE THREAD

**Issue by Stepan007** [vlocityinc/vlocity_build#29]
[exec] (node:88228) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ERROR_HTTP_414: <h1>Bad Message 414</h1><pre>reason: URI Too Long</pre>
     [exec] (node:88228) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[log.txt](https://github.com/vlocityinc/vlocity_build/files/1648869/log.txt)

**Comment by IIvanov8888** [comment]
I saw this error few times before. Are you on the latest version of master ? 
You could try the following Deploy.yaml 
```yaml
projectPath: .
expansionPath: datapack-expanded
buildFile: MyDataPack.json
maxDepth: -1
maximumDeployCount: 1000
defaultMaxParallel: 1
exportPacksMaxSize: null
processMultiple: false
preStepApex:
    Deploy: DeactivateTemplatesAndLayouts.cls
delete: true
activate: true
```
