### ISSUE TITLE
Export of the VlocityTrackingGroup and VlocityDataStore data pack types fails

### ISSUE THREAD

**Issue by maristei** [vlocityinc/vlocity_build#364]
Upon export of the VlocityTrackingGroup and VlocityDataStore data pack types the following errors are displayed:
```
VlocityDataPackType >> VlocityTrackingGroup
  Query >> Select Id, vlocity_cmt__GlobalKey__c from vlocity_cmt____VlocityTrackingGroup__c
  Query Error >> INVALID_TYPE:
vlocity_cmt__GlobalKey__c from vlocity_cmt____VlocityTrackingGroup__c
                               ^
ERROR at Row:1:Column:43
sObject type 'vlocity_cmt____VlocityTrackingGroup__c' is not supported. If you are attempting to use a custom object, be sure to append the '__c' after the entity name. Please reference your WSDL or the describe call for the appropriate names.
  
VlocityDataPackType >> VlocityDataStore
  Query >> SELECT Id, Name FROM vlocity_cmt__VlocityDataStore__c
  Query Error >> INVALID_TYPE:
SELECT Id, Name FROM vlocity_cmt__VlocityDataStore__c
                     ^
ERROR at Row:1:Column:22
sObject type 'vlocity_cmt__VlocityDataStore__c' is not supported. If you are attempting to use a custom object, be sure to append the '__c' after the entity name. Please reference your WSDL or the describe call for the appropriate names.
```
The reason of failure is that file "lib/querydefinition.yaml" contains the following query definitions:
```
VlocityDataStore:
  VlocityDataPackType: VlocityDataStore
  query: SELECT Id, Name FROM %vlocity_namespace%__VlocityDataStore__c

VlocityTrackingGroup:
  VlocityDataPackType: VlocityTrackingGroup
  query: Select Id, %vlocity_namespace%__GlobalKey__c from %vlocity_namespace%____VlocityTrackingGroup__c
```
There are no such objects. Instead the following ones are present:

- vlocity_cmt__DataStore__c
- vlocity_cmt__VlocityTrackingGroup__c

After correction of object names in file "lib/querydefinition.yaml" export does not fail.
Vlocity Build Tool version: 1.13.6
Vlocity version: CMT 900.377.14
