### ISSUE TITLE
Interface Implementation - Deployment

### ISSUE THREAD

**Issue by Stepan007** [vlocityinc/vlocity_build#55]
How can we deploy Interface Implementation object?

**Comment by rutlabaga** [comment]
You should be able to export and deploy interface implementations with the following in your yaml file:
```yaml
queries:
  - VlocityDataPackType: SObject
    query: Select Id from %vlocity_namespace%__InterfaceImplementation__c
  - VlocityDataPackType: SObject
    query: Select Id from %vlocity_namespace%__InterfaceImplementationDetail__c
OverrideSettings:
  DataPacks:
    SObject_InterfaceImplementation:
      MaxDeploy: 5
    SObject_InterfaceImplementationDetail:
      MaxDeploy: 5
```

As well as creating Custom Matching Keys that look like:
![iid](https://user-images.githubusercontent.com/292430/39377929-b8fac0ba-4a0b-11e8-83e3-3415f0f5cfd7.png)
![ii](https://user-images.githubusercontent.com/292430/39377930-b9190ca0-4a0b-11e8-8e64-b157001ff83e.png)
