### ISSUE TITLE
PackExport Error - incorrect SOQL created

### ISSUE THREAD

**Issue by tammersalem** [vlocityinc/vlocity_build#593]
When running a PackExport - I am using a job file that retrieves only IPs and DRs
```
projectPath: .
queries:
  - IntegrationProcedure
  - DataRaptor
```

Yet I keep getting the following error:
```
Error: Invalid URI "/services/data/v54.0/query?q=Select%20Id%2C%20undefinedType__c%2C%20undefinedSubType__c%2CCreatedBy.Name%2C%20CreatedDate%2C%20LastModifiedBy.Name%2C%20LastModifiedDate%20FROM%20undefinedOmniScript__c%20WHERE%20undefinedIsActive__c%20%3D%20true%20AND%20undefinedIsProcedure__c%20%3D%20true"
    at Request.init (/usr/local/lib/node_modules/vlocity/node_modules/request/request.js:273:31)
    at new Request (/usr/local/lib/node_modules/vlocity/node_modules/request/request.js:127:8)
    at request (/usr/local/lib/node_modules/vlocity/node_modules/request/index.js:53:10)
    at /usr/local/lib/node_modules/vlocity/node_modules/request/index.js:100:12
    at createRequest (/usr/local/lib/node_modules/vlocity/node_modules/jsforce/lib/transport.js:84:13)
    at promise.then (/usr/local/lib/node_modules/vlocity/node_modules/jsforce/lib/transport.js:43:5)
    at HttpApi.request (/usr/local/lib/node_modules/vlocity/node_modules/jsforce/lib/http-api.js:82:47)
    at Connection.request (/usr/local/lib/node_modules/vlocity/node_modules/jsforce/lib/connection.js:332:18)
    at /usr/local/lib/node_modules/vlocity/node_modules/jsforce/lib/query.js:410:23
    at tryCallOne (/usr/local/lib/node_modules/vlocity/node_modules/promise/lib/core.js:37:12)
```

I'm on version 1.17.2 (just upgraded from 1.9)
(It appears that for some reason the vlocity namespace is not added

**Comment by AllanOricil** [comment]
@tammersalem add the namespace in ur Job file

**Comment by AllanOricil** [comment]
This is an example of job file with the namespace specified


````yml
projectPath: .
vlocity.namespace: vlocity_cmt
lwcCompilerNamespace: vlocity-cme
lwcCompilerVersion: 900.458.0
expansionPath: vlocity
puppeteerHeadless: true
puppeteerExecutablePath: /usr/bin/google-chrome
````
