### ISSUE TITLE
Custom folder-name isn’t working during extraction

### ISSUE THREAD

**Issue by vivek-the-code-crafter** [vlocityinc/vlocity_build#709]
I was exploring options to give a meaningful name to the folder containing the data pack associated with that object(or records in that object).
PFA the job file I’m using for the extraction. I’m using vanilla VBT without any tools like IDX. Let me know if you see anything obviously wrong in the config. It is always sing global-key, “vlocity_cmt” is valid namespace in the org.

```yaml
projectPath: ./vlocity
manifest:
  - Catalog/BB Only Offers 76 Global
delete: true
activate: true
compileOnBuild: true
maxDepth: -1
useAllRelationships: true
supportHeadersOnly: false
maxBatchSize: 200
performance: true
PaginationSize: 200

OverrideSettings:
  SObjects:
    vlocity_cmt__Promotion__c:
      FolderName:
        - vlocity_cmt__Code__c
      SourceKeyDefinition:
        - vlocity_cmt__Code__c
    vlocity_cmt__DRMapItem__c:
      FilterFields: 
        - vlocity_cmt__UpsertKey__c
```
