### ISSUE TITLE
packDeploy working on scratch orgs but not on developer org

### ISSUE THREAD

**Issue by azorvk** [vlocityinc/vlocity_build#86]
We are trying to deploy vlocity data to our developer edition org but we are getting a lot of unknown errors. Nothing is being deployed to this org because of this. The thing is that the deployment succeeds on recently created clean scratch orgs (which are a copy of our dev org).
Does anybody know what could be the issue here?

This is the command that we use to import the data 
`node_modules/.bin/vlocity -sf.username %env.SF_USERNAME% -sf.password %env.SF_PASSWORD% -job eurofiber-app/vlocity/build/dataPacksJobs/vlocityConfigData.yaml packDeploy`

This is the yaml file
```
projectPath: ./eurofiber-app/vlocity/data
queries:
- VlocityDataPackType: AttributeCategory
  query: SELECT Id FROM %vlocity_namespace%__AttributeCategory__c WHERE %vlocity_namespace%__Code__c LIKE 'EF_%'
- VlocityDataPackType: ObjectClass
  query: SELECT Id FROM %vlocity_namespace%__ObjectClass__c WHERE Name LIKE 'EF_%'
- VlocityDataPackType: PriceList
  query: SELECT Id FROM %vlocity_namespace%__PriceList__c WHERE %vlocity_namespace%__Code__c LIKE 'EF_%'
- VlocityDataPackType: Product2
  query: SELECT Id FROM Product2 WHERE ProductCode LIKE 'EF_%'
- VlocityDataPackType: PricingPlan
  query: SELECT Id FROM %vlocity_namespace%__PricingPlan__c WHERE %vlocity_namespace%__Code__c LIKE 'EF_%'
```

I can post the error logs if necessary but there is only a bunch of unknown errors (not any other error)
This is the final status
Remaining >> 0  
Success >> 0  
Elapsed Time >> 0m 5s  
Error >> 115  

As I said this is fully working using scratch orgs and we don't get any error
Any help would be much appreciated
